#!/usr/bin/with-contenv bash

if [ ! -f "/etc/ssl/certs/ssl-cert-snakeoil.pem" ]; then
  openssl req -new -x509 \
    -days 3650 -nodes \
    -out /etc/ssl/certs/ssl-cert-snakeoil.pem \
    -keyout /etc/ssl/private/ssl-cert-snakeoil.key \
    -subj "/C=US/ST=CA/L=Carlsbad/O=Linuxserver.io/OU=LSIO Server/CN=*"
  chown -R abc:root /etc/ssl/private
fi
