#!/usr/bin/with-contenv bash

HOME="/config"

PERL5LIB=/usr/local/bin/ \
OMP_WAIT_POLICY=PASSIVE \
GOMP_SPINCOUNT=0 \
s6-setuidgid abc \
  vncserver \
    $DISPLAY \
    -disableBasicAuth \
    -SecurityTypes None \
    -AlwaysShared

sleep infinity
